### ISSUE TITLE
Interpreting prediction scores  

### ISSUE THREAD

**Issue by msh-tf** [lyst/lightfm#155]
I built a recommendation model on a user-item transactional dataset where each transaction is represented by 1.

```
model = LightFM(learning_rate=0.05, loss='warp')
model.fit(train, epochs=NUM_EPOCHS, num_threads=NUM_THREADS)
```
Here are the results from the prediction experiment

```
Train auc score:  0.978294
Test auc score : 0.810757

Train precision at k=3:  0.115301
Test precision at k=3:  0.0209936


Train recall at k=3:  0.238312330233
Test recall at k=3:  0.0621618086561
```
Can anyone help me interpret this result? How is it that I am getting such good auc score and such bad precision/recall? The precision/recall gets even worse for 'bpr' Bayesian personalized ranking.

Prediction task

```
users = [0]
items = np.array([13433, 13434, 13435])
model.predict(users, item)
```
Result
```
array([-1.45337546, -1.39952552, -1.44265926])
```
How do I interpret the prediction scores?

Another problem is if I split the data into unequal train test datasets then I get the error

```
print(train.shape)
print(test.shape)
```
(88741, 18109)
(29581, 18109)

`test_auc = auc_score(model, test, train_interactions=train, num_threads=NUM_THREADS).mean()
`
Error

```
/usr/local/lib/python3.5/site-packages/lightfm/lightfm.py in predict_rank(self, test_interactions, train_interactions, item_features, user_features, num_threads)
    658 
    659         if not user_features.shape[1] == self.user_embeddings.shape[0]:
--> 660             raise ValueError('Incorrect number of features in user_features')
    661 
    662         test_interactions = test_interactions.tocsr()

ValueError: Incorrect number of features in user_features
```
Thanks

**Comment by maciejkula** [comment]
1. Train and tests sets have to have the same dimensionality. In your example you have fewer users (30k vs 89k) in the test set, and so user 0 in the test set may not map to user 0 in the training set and so on.
2. In the binary case, you can interpret AUC as the probability that a randomly chosen positive example will be ranked higher than a randomly chosen negative example. Precision at 3 tells you what proportion of the top 3 results are positives. In your case where you have far more than 3 items, it's perfectly possible for positives to be ranked correctly overall (high AUC), but not make it to the top 3 (say, putting your positive at position 4 will give you 0.99 AUC but 0 precision@3). The results you are getting look sensible to me.
3. The prediction scores generally do not have an interpretation. They are simply a means of ranking the items.

Hope this helps!

**Comment by msh-tf** [comment]
Thanks for the reply!

1. I still don't get why train and test set have to be of the same sizes; why does user 0 from test have to match user 0 from train?

2. The input training data is basically a user by item matrix where every interaction is represented by 1 and no interaction is represented by 0. What is a positive/negative example in this case when a predicted var is not explicitly input?

Thanks again.

**Comment by maciejkula** [comment]
1. That's because the model estimates a latent representation for user 0. If you tried to use that representation for any user other than 0 the results may not be very good. 
2. This depends on the training method. In general, negative examples are sampled from the set of items where no interaction was observed. You can read the BPR and WARP papers (linked from docs) for more details.
3. Biases encode mostly item popularity. It looks like in your data popularity is extremely important?

**Comment by maciejkula** [comment]
Closing this for now. Let me know if you have any more questions!

**Comment by kyowill** [comment]
why the prediction score is negative? movie ratings shouldn't be (1,5)? I still don't understand

**Comment by maciejkula** [comment]
@kyowill LightFM is does not predict movie ratings. It is, by and large, an [implicit feedback model](https://jessesw.com/Rec-System/).

**Comment by samshipengs** [comment]
@maciejkula A follow-up question, I trained a model on user purchase history. 1 for an user has purchased this item, 0 otherwise. I would like to make item suggestion to some users.

Just wondering what is the result of model.predict_rank(test)? Is it the recommended item index(or ids) for the test set?

Thanks

**Comment by maciejkula** [comment]
For every non-zero (user, item) pair in `test`, it predicts the position of that item in that user's recommendation list (with smaller numbers being closer to the top of the ranking).

So if you have a non-zero entry in test at (10, 150), the corresponding entry of the result will give you an integer expressing the position of item 150 in user 10's recommendation list.

**Comment by samshipengs** [comment]
@maciejkula Thanks for the quick reply. 
I see, what is the recommendation list for the user? Is it just the list of items we used in training (also testing as they require same number of rows)?

**Comment by maciejkula** [comment]
Yes. The (ordered) list of all items.

**Comment by samshipengs** [comment]
@maciejkula By ordered you mean the same order as how the items were presented in training or? 
So far this is what I understood, for example I have total 1000 items, and I got 42 from predict_rank for (10, 150), then this tells me it's at top 42 position to recommend to this user. So basically the number 42 shows the goodness or 'likelihood' the item 150 to be recommended to this user. And if I were to determine whether I recommend this product to this user or not, I can set a threshold, e.g. if the position is smaller than top 10% ~ 0.1*1000 = 100 then I recommend this item, otherwise not, does this sound right?

I'm new to recommendation system, I only got to know a bit about collaborative filtering through Andrew Ng's coursera class. What do you suggest if I would like to know about the topic and build one at work, reading up the paper listed in the documentation references or just a text book?

Many thanks.

**Comment by maciejkula** [comment]
It gives you the position of item X in a list where you ordered all items by how strongly they are recommended (so yes, 42 is 'goodness', and smaller numbers are better, because they are closer to the head of the list). Of course, if you are actually serving recommendations, you should use the `predict` method (which will give you a score where higher is better).

Recommendations are a ranking problem, not a classification problem, so things like thresholds don't really make sense. The idea is that you have, say, 4 slots to fill in your interface, and you sort all products by their recommendation score and pick the top 4; you never set a threshold.

Reading the references is a good start. The [BPR paper](https://arxiv.org/abs/1205.2618) is a classic. There is also [this](http://www.cs.ubbcluj.ro/~gabis/DocDiplome/SistemeDeRecomandare/Recommender_systems_handbook.pdf) but I can't say anything about how good it is.

**Comment by letotefrank** [comment]
1.I think it（precision_at_k） does not make sense？Because k is random in the train set or test set.
2.How to calculate ？ (def calculate_auc_from_rank)
 
for example, 
ranks is:

-   (0, 0)	0.0
  (0, 2)	1.0
  (0, 3)	3.0
  (0, 5)	4.0
  (1, 0)	0.0
  (1, 1)	1.0
  (1, 2)	2.0
  (1, 5)	3.0
  (2, 1)	0.0
  (2, 2)	1.0
  (2, 5)	2.0
  (3, 0)	0.0
  (3, 1)	1.0
  (3, 2)	2.0
  (3, 5)	3.0
  (4, 1)	0.0
  (4, 2)	1.0
  (4, 3)	2.0
  (4, 5)	3.0
  (5, 0)	0.0
  (5, 1)	1.0
  (5, 2)	2.0
  (5, 3)	3.0
  (5, 5)	5.0

train is:

- 0,0,6.0
0,2,4.0
0,3,3.0
0,5,1.0
1,0,1.0
1,1,2.0
1,2,3.0
1,5,6.0
2,1,2.0
2,2,3.0
2,5,6.0
3,0,1.0
3,1,2.0
3,2,3.0
3,5,6.0
4,1,2.0
4,2,3.0
4,3,4.0
4,5,6.0
5,0,6.0
5,1,5.0
5,2,4.0
5,3,3.0
5,5,1.0

thanks!
