### ISSUE TITLE
LightFM was compiled without OpenMP support

### ISSUE THREAD

**Issue by Tullio-DH** [lyst/lightfm#195]
Hello,

I've installed lightFM inside both python2 and python3 venvs (on a mac OS 10.11) with

`pip install lightfm`

In both environments, when I first load the package I'm getting the following warnings:
```
/Users/tullio.bagnoli/venvs/mktech-py2_7_12_tensorflow/lib/python2.7/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
```

```
/Users/tullio.bagnoli/venvs/mktech-py3_5_2/lib/python3.5/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
```

I can execute the rest of the example jupyter notebooks without problems. How can I fix this?

**Comment by maciejkula** [comment]
Getting OpenMP working on an OSX machine is a [challenge](https://stackoverflow.com/questions/35134681/installing-openmp-on-mac-os-x-10-11).

I would recommend running LightFM in [Docker](https://github.com/lyst/lightfm/blob/master/Dockerfile).

**Comment by rumaniac** [comment]
Hello,
I've installed lightFM inside  python3  for Windows 10 Pc.
I am getting the same error.
![capture](https://user-images.githubusercontent.com/30768963/39721762-238cfa1a-525e-11e8-8b1b-6cbd6d23f3b2.PNG)

**Comment by nbanihasan** [comment]
Hi, I am running lightfm 1.17 on a windows 11 and Python 3.11.4. I am trying to run the sample code provided in the documentation. However the process terminates with:  Process finished with exit code -1073741819 (0xC0000005).
Is the issue related to me running LightFM on windows instead of Linux? Or does it have anything to do with Microsoft Build Tools not being installed correctly?
