### ISSUE TITLE
Most Prediction scores are negative. Is this expected?

### ISSUE THREAD

**Issue by esandoval30** [lyst/lightfm#203]
I am fitting a hybrid model with a coo sparse matrix of 180k users x  2.7k items with 120k interactions (indicated as 1's in this matrix) 

I am using item features (a csr sparse matrix of 2.7k items x 30 features, with valid features for an item indicated by 1's)

I am trying to get predictions for a user and a bunch of items  and the values returned are either negative (in most cases) or zero. 

How should I interpret the score value?

**Comment by esandoval30** [comment]
Quick update: 
I realized that item features needs weights of each feature component rather than 1s or 0s for a item feature being present or not

I also increased the  NUM_EPOCHS 

While I am still get some negative scores, the prediction scores are higher where I am expecting them to be so this is very useful to rank a set of items to recommend to a given user 

It'd still be good to understand/document what the predict method returns (e.g range of values that could be returned)...Alternatively a normalized prediction score value between 0..1 would be useful

**Comment by maciejkula** [comment]
The scores themselves have no meaning in isolation; they are only meaningful because they define a ranking over items for a given user. The scale they take depends on the loss you specify, the learning rate, the regularization parameters, and the data itself.

I recommend keeping an eye on the MRR/AUC scores of your model, and comparing them with what a random or a popularity model would achieve.

**Comment by esandoval30** [comment]
Thanks, Maciej. Very helpful
