### ISSUE TITLE
Interpreting evaluation values

### ISSUE THREAD

**Issue by kahrkunne** [lyst/lightfm#255]
I'm having trouble interpreting the evaluation metrics in lightfm.evaluation. For example, with our current configuration we get the following outputs:

```[Precision@k] Train precision: 0.53
[Precision@k] Test precision: 0.35
[Recall@k] Train precision: 0.19
[Recall@k] Test precision: 0.09
[AUC] Train precision: 0.99
[AUC] Test precision: 0.96
[Reciprocal Rank] Train precision: 0.70
[Reciprocal Rank] Test precision: 0.57
```

For each of these I know what they mean, and I generally know that higher = better, but I have no clue how "good" these values are, or what to expect.

Similarly, if I fit and evaluate a model on an implicit feedback version of our data (all scores set to 1), I get exactly the same numbers, but the models give different recommendations. How do I interpret this?

Obviously these are *very* similar, but the output of the two models is somewhat different. How do I interpret this?

**Comment by maciejkula** [comment]
In general, it's difficult to say what a 'good' value of a metric is. This
depends hugely on the dataset you have. The best way of figuring out what a
good model is for your data is to try lots of different models and compare
them.

LightFM implements implicit feedback algorithms: passing in rating values
has no effect on the model. Fitting the same model repeatedly will give
slightly different results each time due to randomness inherent in the
fitting process.




On 21 Jan 2018 11:25, "Kahr Kunne" <notifications@github.com> wrote:

I'm having trouble interpreting the evaluation metrics in
lightfm.evaluation. For example, with our current configuration we get the
following outputs:

[Precision@k] Test precision: 0.35
[Recall@k] Train precision: 0.19
[Recall@k] Test precision: 0.09
[AUC] Train precision: 0.99
[AUC] Test precision: 0.96
[Reciprocal Rank] Train precision: 0.70
[Reciprocal Rank] Test precision: 0.57

For each of these I know what they mean, and I generally know that higher =
better, but I have no clue how "good" these values are, or what to expect.

Similarly, if I fit and evaluate a model on an implicit feedback version of
our data (all scores set to 1), I get exactly the same numbers, but the
models give different recommendations. How do I interpret this?

Obviously these are *very* similar, but the output of the two models is
somewhat different. How do I interpret this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lyst/lightfm/issues/255>, or mute the thread

**Comment by kahrkunne** [comment]
LightFM only implements implicit feedback? Then why does the documentation start with (emphasis mine:) "LightFM is a Python implementation of a number of popular recommendation algorithms for both implicit _and explicit_ feedback."

**Comment by maciejkula** [comment]
Well, there is also an explicit binary feedback algorithm that is quite bad and you shouldn't use. It's here for backward compatibility but I may well remove it.

**Comment by Saba101** [comment]
Well, the question wasn't answered. nobody said how to interpret the values.. what does a` [Precision@k] Test precision: 0.35` mean? It understood model was able to get precision of 35% only, but how do we understand it - what does it says about the data that was given to the model for evaluation?
