### ISSUE TITLE
Content based component in lightFM does not seem to work?

### ISSUE THREAD

**Issue by moggeandersson** [lyst/lightfm#373]
Hello and thanks! Is there a way to use this algorithm as a pure tag suggestion algorithm? I have tried to train the model with only a rich item-feature matrix and an interaction matrix in form of the identity matrix, which should imply that there are no users with similar preference for any item, that means the algorithm leans towards content-based recommendations? But when I use the get similar tags for example, the result does not really feel relevant at all. 

For example, for the tag "airplanes", I first get the tag "airplanes" which indicates that everything is alright, it should be most similar to itself, however the next tag is "dancing" and other random tags which does not make sense. There is a lot of items with tags similar to Airplanes, like aircraft, planes etc.  Do I misunderstand the fundamentals with your algorithm or is my model simply wrong?

**Comment by DoronGi** [comment]
Since you don't feed your model with any real interaction data, all it can learn is the tags co-occurrences (meaning if all airplanes are also tagged as aircrafts, we can expect similarity between these tags embeddings). There is the question of why would you use such a complicate method to find this similarity, instead of simply counting the number of times each tag-pair occurs together or something of that sort.

Anyway, I think what you suggest can potentially work, and suggest you will try the following:

1. Make sure your item feature matrix doesn't include an identity part (meaning every item is described only by its features, without an identity feature). Your call when constructing the dataset should be as follows:
```lightfm.data.Dataset(item_identity_features=False)```
Without it the model could reach perfect fit just by using the identity feature to match between all user-item pairs.

2. Play with your model ```item_alpha```, specifically try to increase it (default is 0). This will prevent over-fitting your interaction matrix which is very sparse. I would try values between 0.1 to 0.001, but that is just a guess.

3. Generate a bigger interaction matrix. As long as you generate it randomly, I don't think there is any problem in having as many users as you like, and having each user interact with several items. This should again help with over-fitting. 

4. Try reducing the number of components in your model, again to avoid overfit. 

But again, if it is only for the purpose of experimenting and education, go ahead. Otherwise I suggest you will try a different approach. When providing the model with real data, you get significant tag similarity. You may get that golden-retriever is similar to Labrador since users that were interested in one were also interested in the other. In your can you will be lucky to get that both are similar to dogs (if items tagged with Labrador are also with dogs) and extremely luck to get similarity between the breeds.

**Comment by moggeandersson** [comment]
Thanks a lot, that gave me great insight!

**Comment by maciejkula** [comment]
This is a great answer. Thanks, @DoronGi!

**Comment by DoronGi** [comment]
Glad to help. And thank you for this great package! So well written and documented, a real pleasure!
