### ISSUE TITLE
Find similar items in combination with item features.

### ISSUE THREAD

**Issue by DPGrev** [lyst/lightfm#374]
First of all, thank you for creating this library it works very well.

I am trying to find similar items within the model for which I used the following function:

```python
def similar_items(internal_idx, item_feats_mtx, model, N=10):
    item_representations = model.get_item_representations()[1]

    # Cosine similarity
    scores = item_representations.dot(item_representations[internal_idx, :])
    item_norms = np.linalg.norm(item_representations, axis=1)
    scores /= item_norms

    best = np.argpartition(scores, -N)[-N:]
    return sorted(zip(best, scores[best] / item_norms[internal_idx]),
                  key=lambda x: -x[1])
```
However if I add item features to the model and train it the size of the `item_representations` changes and the new item features are added to the item representations. 

Would I still be able to calculate similar item by using:

```item_representations = model.get_item_representations()[1][0:N_items]```

Where num_items is the number of items?

With other words, do the first N item embeddings still represent the N items when item features are added?

**Comment by DoronGi** [comment]
When using item features, your call to ```model.get_item_representations``` should include the feature matrix as input: ```get_item_representations(features=item_features)```, see documentation:
```
Parameters: features (np.float32 csr_matrix of shape [n_items, n_item_features], optional) – 
Each row contains that item’s weights over features. An identity matrix will be used
if not supplied.
```

In your code, assuming you used ```lightfm.data.Dataset``` to arrange your data, you would generate similarities based only on the identity feature of each items (since they are the first ones created as can be seen here : https://github.com/lyst/lightfm/blob/3e42e3e74ea5eb9e39be2a571a214a15f411a667/lightfm/data.py#L207
), which is OK to do, but doesn't represent the items fully (as they were trained).

**Comment by DPGrev** [comment]
Thank you, this made the issue clear.
