### ISSUE TITLE
User/Item features shape

### ISSUE THREAD

**Issue by Sammckay12** [lyst/lightfm#394]
Hi! 

In my interactions matrix I have 21561 users and 2889 items. When I build_user_features I have a feature list of length 62. The resulting user_features.shape is (21561, 21623). Should the shape not be (21561, 62) ? 

What I have noticed is the resulting '21623' is the full list of users + the 62 features. 21561 + 62 = 21623. When viewing a specific users features and seeing input in the nonzero input is: 

user_features[202].nonzero()
(array([0, 0, 0], dtype=int32), array([  202, 21579, 21591], dtype=int32))

user_features[67].nonzero()
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([   67, 21562, 21566, 21567, 21575, 21586, 215 88, 21615, 21616,21617, 21620, 21622], dtype=int32))

first value in the array is the user number, followed by the applicable features to that user starting from 21561 => 21623. Is this the expected behaviour and shape of the user/item features?

Thanks for any help! First foray into this area!

**Comment by maciejkula** [comment]
This is because by default, LightFM allocates a separate feature for every user and item: think of these as embeddings/vectors that encode each user and item, and how they related to each other. This is where most of the model's expressive power comes from. 

To see this, you can disable the `user_identity_features` and `item_identity_features` options in the constructor for the `Dataset` [class](http://lyst.github.io/lightfm/docs/lightfm.data.html#lightfm.data.Dataset) and compare the accuracy you get out of the model.

**Comment by marielen** [comment]
Hi!

When I have `user_feature` not built by Dataset class, do I need to put together with the identity matrix?

Thanks.

**Comment by Chirag-Amin** [comment]
You don't have to stack the identity matrix as @maciejkula mentioned, if you are not interested in the latent vectors for your `user_features` then you can forgo this step.  

If you are interested in creating the latent vector without using the `Dataset` class then have a look at this blog: https://www.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/. Although I would suggest using the `Dataset` class.

**Comment by ailurus1991** [comment]
@maciejkula thanks for your explanation, but I got another question. When I got a model trained with user-item interactions and item_features, does the model.predict will return both the item id and feature ids?(like the tag id, because they are in item_features)

I wanna get similar items with a trained model built on interactions and item features, but I got some tag ids, not only the item ids....

**Comment by andrewng88** [comment]
> This is because by default, LightFM allocates a separate feature for every user and item: think of these as embeddings/vectors that encode each user and item, and how they related to each other. This is where most of the model's expressive power comes from.

Thanks for your explanation but I still did not catch the columns part for building the user and item feature matrix and I have read the docs.

Return type: | CSR matrix (num items, **num features**)
-- | --

For example,

I have 2 items and their features are A, B , C and X, Y , Z
So the CSR matrix should be 2 x 6 but it's not the case as experienced by the OP.

Can you please elaborate in a simpler manner? Thanks.

**Comment by andrewng88** [comment]
> This is because by default, LightFM allocates a separate feature for every user and item: think of these as embeddings/vectors that encode each user and item, and how they related to each other. This is where most of the model's expressive power comes from.

So, for user features matrix,

the row would be user , the column would be user and set(user features ).  
Can you please explain why we need to replicate user at both row and columns? 

Please advise. Thanks

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
