### ISSUE TITLE
rand_r missing stdlib.h on Windows

### ISSUE THREAD

**Issue by gglanzani** [lyst/lightfm#41]
Hi was wondering if we could use [rand_s](https://msdn.microsoft.com/en-us/library/sxtz2fa8.aspx) when compiling under windows because compiling as-is does not work. Compiling by replacing rand_r by rand_s does work instead.

**Comment by maciejkula** [comment]
This is due to the fact that `rand_r` is part of `glibc` which you are obviously not using.

It may work for you as-is if you use `gcc` for compilation. Alternatively, I have opened https://github.com/lyst/lightfm/pull/42 which includes its own `rand_r` implementation. I obviously cannot use MSVC's impl as that would only compile on Windows!

Having said that, you may run into more problems still with openmp support and so on; I cannot support Windows myself but would be happy to accept changes that make it work on Windows.

**Comment by maciejkula** [comment]
It would be great if you could check out  #42 and see if it solves your problem.

**Comment by gglanzani** [comment]
@maciejkula #42 compiles on my machine. Will keep you posted if I incurs into openmp issues

**Comment by maciejkula** [comment]
Thanks, please let me know if you succeed in using it.

**Comment by maciejkula** [comment]
Does it work fine?

**Comment by gglanzani** [comment]
Hi Maciej, I'm expecting to have some time on Wednesday afternoon. I promise to let you know by then (like, really promise!)

**Comment by gglanzani** [comment]
@maciejkula Contrary to my promise, I tried it a little earlier (now). It works (i.e. in the example notebook I arrived up until the AUC score, so I guess that's enough to test the openmp).

**Comment by maciejkula** [comment]
Fantastic, I'll merge my changes and cut a new release.
