### ISSUE TITLE
Does lightfm has a gpu based implemetation?

### ISSUE THREAD

**Issue by treper** [lyst/lightfm#429]
Training is slow even using multi-core processors. I have 5 million users, 40000 items and 25 user features, it cost me 10 hours to train on a 16 core machine. Can lightfm support training with gpu, maybe this will accelerate training a lot.

**Comment by nazmiasri95** [comment]
I'm not sure whether they have plan for GPU based implementation or not but I suggest that you only take top 1 million active users (for example) instead of taking all users. You might want to reduce it since you have resources limitation. 

But if it can support GPU, for sure it will help to accelerate training a lot. :D Cheers

**Comment by rth** [comment]
https://github.com/maciejkula/spotlight has a similar implementation, as far as I understand, based on PyTorch (that supports GPU).

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
