### ISSUE TITLE
How is AUC calculated in lightfm

### ISSUE THREAD

**Issue by Ivanclj** [lyst/lightfm#444]
Hi all,

I was wondering how lightfm calculates AUC scores. In the doc it says it's the probability that a randomly chosen positive example has a higher score than a randomly chosen negative example. A perfect score is 1.0. So does lightfm just randomly choose a positive example and calculate the percentage of cases where the score of the positive example is higher than a randomly sampled negative example for couple of times?  Is there a reasoning for why not use the standard AUC formula where it's equal to true positive rate (number of positive items in top k list/ all positive items) / false positive rate (number of negative items in top k list / all negative items) ?  

Thanks so much!

**Comment by maciejkula** [comment]
It does use the standard formula. It just offers a more intuitive explanation in the docs.

**Comment by frogben** [comment]
Can you explain it? For example?

**Comment by xaviml** [comment]
If it uses a standard AUC formula. How many top-N recommendations are taken into account to compute true positive rate and false positive rate? For a normal binary classification, defining the TPR and FPR is easy since it's either correct or incorrect. However, in the case of a recommendation system is needed to define how many recommended items the RecSys will give out and this needs to be set to compute AUC.

Thank you for your patience and for this amazing project! @maciejkula

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
