### ISSUE TITLE
In the example code of movielen,why value of element of interaction matrix which is positive not sets to be 1 but original rating?  

### ISSUE THREAD

**Issue by BruceChen2017** [lyst/lightfm#468]
```
def _build_interaction_matrix(rows, cols, data, min_rating):

    mat = sp.lil_matrix((rows, cols), dtype=np.int32)

    for uid, iid, rating, _ in data:
        if rating >= min_rating:
            mat[uid, iid] = rating

    return mat.tocoo()
```

**Comment by BruceChen2017** [comment]
@maciejkula

**Comment by batuyildiz** [comment]
This is because explicit rating performs worse than implicit rating (having rated X for movie vs having rated the movie at all).

Think of it this way if you gave 1 start to a movie, that means you SELECTED to watch it (title, genre, poster etc.) made you watch it, which is a stronger signal than not having liked it.

Even if a great movie that you would definitely love is recommended you, if it's not the genre you like, you won't click and watch, so recommending 5 items to user for him to click performs better with implicit ratings.

This is my couple of sentences of interpretation, for author's explanation please watch:
https://skillsmatter.com/skillscasts/11375-explicit-vs-implicit-recommenders

**Comment by EralpB** [comment]
This is because explicit rating performs worse than implicit rating (having rated X for movie vs having rated the movie at all).

Think of it this way if you gave 1 start to a movie, that means you SELECTED to watch it (title, genre, poster etc.) made you watch it, which is a stronger signal than not having liked it.

Even if a great movie that you would definitely love is recommended you, if it's not the genre you like, you won't click and watch, so recommending 5 items to user for him to click performs better with implicit ratings.

This is my couple of sentences of interpretation, for author's explanation please watch:
https://skillsmatter.com/skillscasts/11375-explicit-vs-implicit-recommenders

**Comment by BruceChen2017** [comment]
@EralpB But according to my test, if I change explicit rating to 1 within positive cases,I get the same result

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
