### ISSUE TITLE
Encode NaN values in the sparse matrix

### ISSUE THREAD

**Issue by marcellosusanto** [lyst/lightfm#471]
Hello first of all I want to give my thanks for making this beautiful package. It really help me learn how to make recommendation system really well. Keep up the good work !

Here I want to ask some question about how to encode the input for the model. I have an e-commerce dataset basically tell wether someone view/buy an item and the data is really sparse. It have many NaN values in the matrix.

I try to make the matrix the Dataset Class and I notice that it encode the NaN values (meaning we don't know wether te user is view/buying this ite) to 0, same with the encoding I use for an item the user only view (yet). I think this will create a false prediction because now the model think that NaN values are the same as the item the user only view, or am I wrong ?

Is it better to encode the NaN values as 0, view as 1, buy as 2, or are there a better way to encode it ?

**Comment by EralpB** [comment]
I think you can't say like 1 is view 2 is buy 3 is bookmark etc. it's not how implicit recommendation works, my suggestion is run your algorithm 2 times, one for views and one for buys then combine them together, like 5 products from first result 5 products from second result..

or you could combine view + buys to one signal like 1 if user bought OR viewed, 0 else, so implicit interest in that item, and run just once.

**Comment by marcellosusanto** [comment]
Hi thanks for the reply EralpB
For your first suggestion I already tried making the model using only 'buy' event and it turns out really bad LOL. I only got test AUC score of 0.49 which is even lower than the baseline 0.5. This makes sense because the 'buy' event is really rare making the matrix even more sparse than before. So if possible I want to keep the 'view' event too

For your second suggestion, that is the exactly the first model I make and the AUC score is good (0.88). But I have my concern about the result, because if I use that kind of encoding I think the model will think that 'view' and 'buy' are the same event but in reality 'buy' represent more interest than 'view'. I read the LighFM documentation and fount out you can make a weight matrix using Dataset Class and train the model using that weight matrix (as sample_weight). Is this a good practice or not ?

Beside that I try read a paper about implementation of LightFM in Lyst (made by the author of LightFM) and in it he mention about the way he encode Movie lens dataset where a rating below 4 as negative and a rating from 4 to 10 as positive. I dont really understand what its mean 
![image](https://user-images.githubusercontent.com/36285137/60566813-3f0b4500-9d92-11e9-82ed-3863563aac13.png)

**Comment by EralpB** [comment]
Hi, no problem, just mind that I'm not an expert, you can use weights, so for buy you can give a weight of 1 and for view you can give a weight of 0.5, what weight does in this model/training is that, if a badly-recommended product is found and the weight for this interaction is bigger, it takes a bigger step to escape out of that bad area of the function, so you can use it, I'm not sure if that will make a big difference though. 

in this paragraph again implicit is only 1 or 0, nothing else, and converting from 0,1,2,3,4,5 to 0,1 space you have many options, you can treat 0 as 0 and everything else is 1 (like this repo's example does)

or you can treat 123 as 0 and 45 as 1, which this paragraph does, so basically removes all interactions with low ratings from the dataset.

I'm glad you are comparing every step/algorithm by AUC because sometimes things work against intuition!

my personal opinion is differentiating between view and buy is micromanaging if you have a very sparse matrix.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
