### ISSUE TITLE
How to get more transparency on how recommendations are being generated

### ISSUE THREAD

**Issue by kshitijyad** [lyst/lightfm#493]
Hi, Thank you for this amazing framework. 
I actually wanted to know if there is a way of gathering more information how a user is being recommended some product based on viewership. I understand that the matrix is being decomposed into its latent variables, but If i want to explain it to business folks how these recommendations were being recommended to the user, how do I do that?

Is there a way to show how user is similar to a group of other user because of which he is being recommended a particular set of recommendations? I am looking for more transparency here. Is it possible?

**Comment by kshitijyad** [comment]
You will have to manually tweak that. The login is that give all the items purchased a large negetive value so that the recommendation score for those items become very low and doesn't come in the top recommended results.

Interation is the sparse interaction matrix.
Click content is the content which was click/purchased


 ```
        clicked_content = interactions[user,:].toarray() # Get the ratings from the training set ratings matrix
        clicked_content = clicked_content.reshape(-1) + 1 # Add 1 to everything, so that items not purchased yet become equal to 1
        clicked_content[clicked_content > 1] = -10 # Make everything already purchased high negetive
        
        predictions=self.model.predict(user,np.arange(len(self.itemID_to_index)))
        recommendations=clicked_content+predictions
```

**Comment by impaktor** [comment]
Perhaps test dimensionality reduction of latent space? Like a tSNE or UMAP?

Or better, just explain to "business folks" how matrix factorization works?

**Comment by FrancescoI** [comment]
As @impaktor said, compressing your user o item latent features into a 2D space helps to visualize user/item clusters.

But if you look for a more interpretable model, you should check within the "additive model" family such as non-negative matrix factorization. Non-negativity helps (1) by inducing sparsity in the latent structures (so that just a few of them will be more than 0 for any user and item) and (2) by making your latent features more simple to interpret (if a customer has all latent features valued 0s except for one, you will recommend him only items with the same latent feature valued more than 0!)

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
