### ISSUE TITLE
What is the right way (format) to input user features to the build_user_features function?

### ISSUE THREAD

**Issue by clementechiu** [lyst/lightfm#494]
I have been struggling for a while now trying to input my user features into lightfm to try to include them in my recommendation model. I have read many other issues refering to similar problems, but I still can't manage to work solve my problem. 

I have my data in a pandas dataframe. My user IDs are strings like `"AHS-1"`, and I'm trying to include one user feature to start. For what I've read, the format in input user features into the build_user_features function is:

[user_id1, [user_feature1, user_feature2],
[user_id2, [user_feature1, user_feature2] ...] 

I've tried many options to create this, the latest being creating a dataframe with the user IDs and the feature, then converting this into a tuple, but I get the error "TypeError: 'int' object is not iterable" since my feature is an int. 

Here's my code:

```
user_features_pd=pd.concat([user_data['mber_id'],user_data.iloc[:,5].astype(int)], axis=1) 
tuples = [tuple(x) for x in user_features_pd.values]
user_features = dataset.build_user_features((tuples))
```

I would appreciate very much any help!

**Comment by clementechiu** [comment]
`
user_features_pd=pd.concat([user_data['mber_id'],user_data.iloc[:,5].astype(int)], axis=1) \n
tuples = [tuple(x) for x in user_features_pd.values] \n
user_features = dataset.build_user_features((tuples))
`

**Comment by Med-ELOMARI** [comment]
Hi @clementechiu  ,

i created a small example in thi [repo](https://github.com/Med-ELOMARI/LightFM-Dataset-Helper) with a class  i have worked with months ago .

here is how i manage to prepare the features 

https://github.com/Med-ELOMARI/LightFM-Dataset-Helper/blob/7b023db4ebe3df5249589ddfcd941bd0aa002525/DatasetHelper.py#L177-L181

the function explains itself , for any other questions i'll be happy to help

**Comment by clementechiu** [comment]
Hi @Med-ELOMARI ! Thank you very much for your answer, I really appreciate it.

I tried running my code using the format you used. I obtained a tuple of the form:

```
(['1-UMF', ['62']],
 ['1-M26', ['21']],
 ['1-1J5T', ['33']])
```

Where the first element is the user id and the second is the one feature I'm trying to add to the model. If I understand well, this is the format I should use for `build_user_features`. However, after trying to pass this to the function, I get the error `Feature 62 not in eature mapping. Call fit first.`

So I now have the doubt whether I should also include the feature name in the tuples or not. For what I understand, you didn't do this in your code, so I would appreciate if you could tell me how did your sort out this problem, or if you did it somewhere else.

Thanks in advance!

**Comment by Med-ELOMARI** [comment]
well , the error explain itself (Feature 62 not in eature mapping. Call fit first) , i think you used just the function that i mentioned . i recommend you to use the whole class , that will fit every unique existing feature before building it . 

let's pic a super 😄  small example , here we have this interactions : 

|   | item_X  | item_Y  | item_Z  |
|---|---|---|---|
| user_A | 0  | 5  | 1  
| user_B | 1 |   |      
| user_C |   | 5  |   

with this users details :

|   |   |   |   | 
|---|---|---|---|
| user_A |  user_feat1 | user_feat2 
| user_B |  user_feat3 | user_feat4 | user_feat2
| user_C |  user_feat1 | user_feat4

and items details : 

|   |   |   |   | 
|---|---|---|---|
| item_X |  item_feat1 
| item_Y |  item_feat2 | item_feat3 | item_feat4
| item_Z |  item_feat1 | item_feat3 | item_feat4

so  the right way or format to present the data is :

```python 
interactions = [
    ("user_A", "item_X", 0),
    ("user_A", "item_Y", 5),
    ("user_A", "item_Z", 1),
    ("user_B", "item_X", 1),
    ("user_C", "item_Y", 5),
]
users_features = (
    ["user_A", ["user_feat1", "user_feat2"]],
    ["user_B", ["user_feat3", "user_feat4", "user_feat2"]],
    ["user_C", ["user_feat1", "user_feat4"]],
)
items_features = (
    ["item_X", ["item_feat1"]],
    ["item_Y", ["item_feat2", "item_feat3", "item_feat4"]],
    ["item_Z", ["item_feat1", "item_feat3", "item_feat4"]]
)
```
first we create a Dataset instance 
```python 
from lightfm.data import Dataset
dataset = Dataset()
```
then we must fit all the data you have , users , items , all features 
this step is essential because the *LightFM* model understand numbers not strings , so we will need to map each string we have to a number  , and that's what *dataset.fit* do
```python 
dataset.fit(
    users=["user_A", "user_B", "user_C"],
    items=["item_X", "item_Y", "item_Z"],
    item_features=["item_feat1", "item_feat2", "item_feat3", "item_feat4"],
    user_features=["user_feat1", "user_feat2", "user_feat3", "user_feat4"],
)
```
you can see the feature_mapping is a dict of mappings for our data
![image](https://user-images.githubusercontent.com/11338137/67134178-0d1ed100-f211-11e9-86dd-98fbd80885f5.png)

then we can build the rest (assuming everything we will add here is already fitted (Mapped) in the last step) :
```python 
(interactions, weights) = dataset.build_interactions(interactions)
user_features_list = dataset.build_user_features(users_features)
item_features_list = dataset.build_item_features(items_features)
```

then we can feed our model 
```python 
model = LightFM(no_components=24, loss="warp", k=15)
model.fit(
    interactions=interactions,
    sample_weight=weights,
    item_features=item_features_list,
    user_features=user_features_list,
    verbose=True,
    epochs=10,
    num_threads=20,
)
```

to predict , we give the mappings as input , not the strings (user_A ....)
```python
print(model.predict(1, list(range(3))))

```
Results [-0.15689075  0.10851561 -0.19980735]

hope i makes it clear now , ask if not 😵 
good luck 🍀

**Comment by clementechiu** [comment]
Thank you very much again for the kind response. 

When building the user features, I followed the same steps described above, including the `dataset.fit` specifying the names of the user features.  

It works with some variables as user features. However, when I try including others, it returns the error `Feature "something" not in eature mapping. Call fit first.` even though I did call fit including that variable.

I've tried with different types of variables, and apparently the problem seems to be with string variables I intented to use as categorical, or continous variables with large values, which maybe LightFM tries to encode as categorical. Would you happen to know if the cause of the problem could be the way I'm inputing my variables to LightFM? Or if there is any other possible problem that causes this error to pop up?

**Comment by Med-ELOMARI** [comment]
Hi @clementechiu  , can i see those variables that gave you the error , maybe there some Latin or special characters there , if not , the fit method works on everything it's just a mapping as a dict object .

second thing i worked with Strings and continuous variables , it works on everything , but it's not logic to use it on really huge amount of  continuous  variables . try to simplify it to chunks and each chunk is a feature ( ex : years from 1900 to 2019 can be split to centuries ) to reduce the amount of data .

check this issue : https://github.com/lyst/lightfm/issues/433 and @maciejkula  answers 

Your questions :
1. i can have a clear view if i see this input data 
2. this problem is just from the why you input data or the data encoding

good luck 🤞

**Comment by clementechiu** [comment]
Ok thank you very much @Med-ELOMARI ! I think my problem is probably that I was inputting my continous variables wrong (not as a dictionary with weights as suggested in an answer of the issue #433). I tried splitting it into chunks as you suggested and it works. Thank you very much for your help!
