### ISSUE TITLE
User - Item interaction weights optimisations

### ISSUE THREAD

**Issue by Gaurav470** [lyst/lightfm#518]
Hi,
My data consists of user and item interactions with ratings to be set with a custom  function. But initially I tried setting ratings manually to the interactions between the users and items, firstly some high positive ratings with large variations (eg - 10, 20 ,100 etc) and then simply setting the rating as one (1) for all interactions.
Then i trained the model for both separately and called for model.predict function which showed  the predicted ratings to be almost same for both the methods.
Can anyone please help out to suggest what can be done to give the predicted rating a much higher value for those whose rating initially has been set high.
@maciejkula if you can look into this, it will be really helpful.
Thanks

**Comment by FrancescoI** [comment]
Keep in mind that WARP (neither BPR) doesn't reconstruct the original scores, since it doesn't minimize the squared errors, but it (sort of) learns a function that map the original item rankings to the final scores you get when using the predict method (or making the dot product between user and item embeddings plus the biases). 

Weights are used in the gradient descent to make greater/smaller updates accordingly. To you is just how much confidence you are that this (user,item) pair is really positive!
