### ISSUE TITLE
different users in training and test set

### ISSUE THREAD

**Issue by tim2tim** [lyst/lightfm#98]
Hello,
the question here is:
How to deal with different users in training and test set?
In the example on the hybrid model for question recommendations to users
(https://github.com/lyst/lightfm/blob/master/examples/stackexchange/hybrid_crossvalidated.ipynb)
the model recommends the highest ranked question (item) to the user not answered by this user yet.
What about this different setting:
Each user only interacts with one item. 
Training is done with these interactions
At test time, there is a new user.
The aim is to recommend the highest ranked item for this unknown user.
This means that the aim of this setting is to deal with different users in training and test set but always the same set of items.
Is this possible? How can this be achieved?
It would be appreciated very much if you could give an example or point to an existing example where this problem is tackled.
Thank you!

**Comment by maciejkula** [comment]
LightFM is designed to be able to deal with this problem.

You do this via user features: as long as each user is described by a set of features and these features are shared between the training and the test set, you will be able to make predictions in the test set.

Suppose you describe each user by their unique id and their country of origin. While training, you estimate parameters for the id feature and the country feature. At test time, you can use the country feature to provide prediction even for a user whose id isn't part of the testing set. (You couldn't do this if you didn't have the country feature, because there would be no way of estimating the representation for a new user.)

This is exactly equivalent to the [StackExchange](https://github.com/lyst/lightfm/blob/master/examples/stackexchange/hybrid_crossvalidated.ipynb) example, but instead of using item features (in this case, question tags) you would use user features (by passing them to the [fit](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.fit) and [predict](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.predict) methods).

**Comment by maciejkula** [comment]
Does my answer help?

**Comment by DeoLeung** [comment]
Hi @maciejkula ,

May I ask your help about the features, as you mentioned we can use ['user_id', 'country'] as features.
supposed we have 1000 user and 100 country, how to construct the features will be better?
1. should I normalize them into 1? like user_id == 0.001, country = 0.01
2. for small feature, like country, expand it to multiple features, like ['country a', 'country b' ...] and mark the related one to 1, similar to the stackoverflow tags.
3. or is there any instruction on how to weight the features? e.g if I define userid from [0, 1000), country [0, 100), will user_id be over weighted 10 times?

thank you
